import type { GameDef, PicoloCard, TruthCard } from '../types'

export const CATEGORIES = [
  { id: 'all', label: 'Tous' },
  { id: 'classique', label: 'Classiques' },
  { id: 'cartes', label: 'Cartes' },
  { id: 'casino', label: 'Casino' },
  { id: 'defis', label: 'Défis & votes' },
  { id: 'rapide', label: 'Rapides' },
] as const

export const GAMES: GameDef[] = [
  {
    id: 'casino',
    title: 'Roulette Casino',
    tagline: 'La boule décide qui trinque',
    description:
      'Vraie roulette européenne. Rouge, noir, zéro, numéros spéciaux : chaque case a sa règle pour boire.',
    minPlayers: 2,
    image: '/images/game-casino.jpg',
    accent: '#22c55e',
    duration: '10–30 min',
    category: 'casino',
  },
  {
    id: 'picolo',
    title: 'Défis Picolo',
    tagline: 'Cartes aléatoires, chaos garanti',
    description: 'Défis, gorgées et règles maison. Passe le téléphone et survit… ou pas.',
    minPlayers: 2,
    image: '/images/game-picolo.jpg',
    accent: '#f43f9d',
    duration: '15–40 min',
    category: 'classique',
  },
  {
    id: 'jamais',
    title: 'Je n’ai jamais',
    tagline: 'Avoue… ou bois',
    description: 'Si tu l’as déjà fait, tu bois. Les secrets sortent plus vite que les bouteilles.',
    minPlayers: 2,
    image: '/images/game-never.jpg',
    accent: '#a78bfa',
    duration: '10–25 min',
    category: 'classique',
  },
  {
    id: 'vote',
    title: 'Qui est le plus…',
    tagline: 'Le groupe décide, quelqu’un trinque',
    description: 'Votez du doigt. La personne désignée boit. Révélations garanties.',
    minPlayers: 3,
    image: '/images/game-vote.jpg',
    accent: '#fb7185',
    duration: '10–20 min',
    category: 'defis',
  },
  {
    id: 'verite',
    title: 'Action ou Vérité',
    tagline: 'Version apéro, conséquences incluses',
    description: 'Vérité embarrassante ou action osée. Refuser ? Cul sec.',
    minPlayers: 2,
    image: '/images/game-truth.jpg',
    accent: '#22d3ee',
    duration: '15–30 min',
    category: 'defis',
  },
  {
    id: 'bouteille',
    title: 'La Bouteille',
    tagline: 'Tourne, pointe, bois',
    description: 'Fais tourner la bouteille. Le désigné subit le défi du moment.',
    minPlayers: 3,
    image: '/images/game-bottle.jpg',
    accent: '#fbbf24',
    duration: '5–15 min',
    category: 'rapide',
  },
  {
    id: 'bataille',
    title: 'Bataille',
    tagline: 'Deux jeux de cartes, un seul survivant',
    description:
      'Chacun a un jeu de 52 cartes. Séries, avantages, boucliers et chutes x2. Égalité = bataille !',
    minPlayers: 2,
    image: '/images/game-bataille.jpg',
    accent: '#f472b6',
    duration: '10–30 min',
    category: 'cartes',
  },
  {
    id: 'roi',
    title: 'Le Roi (Kings Cup)',
    tagline: 'Le classique des cartes & shots',
    description: 'Tire une carte, applique la règle. Le 4e roi finit le verre du milieu.',
    minPlayers: 2,
    image: '/images/game-kings.jpg',
    accent: '#f97316',
    duration: '20–45 min',
    category: 'cartes',
  },
  {
    id: 'roulette',
    title: 'Roulette Cul Sec',
    tagline: 'Roue simple, destin brutal',
    description: 'Une petite roue d’apéro. Gorgées, passe, cul sec. Zéro stratégie.',
    minPlayers: 2,
    image: '/images/game-roulette.jpg',
    accent: '#34d399',
    duration: '5–10 min',
    category: 'casino',
  },
  {
    id: 'minibus',
    title: 'Le Mini-Bus',
    tagline: 'Plus haut, plus bas, plus soûl',
    description: 'Devine si la prochaine carte est plus haute ou plus basse. Rate = tu bois.',
    minPlayers: 2,
    image: '/images/game-bus.jpg',
    accent: '#60a5fa',
    duration: '10–25 min',
    category: 'cartes',
  },
  {
    id: 'pyramide',
    title: 'La Pyramide',
    tagline: 'Mémoire + cartes = gorgées',
    description:
      'Mémorise tes cartes, puis la pyramide se révèle. Tu as la carte ? Tu donnes. Sinon tu bois.',
    minPlayers: 2,
    image: '/images/game-pyramid.jpg',
    accent: '#c084fc',
    duration: '15–35 min',
    category: 'cartes',
  },
  {
    id: 'dealer',
    title: 'Ride the Bus',
    tagline: '4 questions, 4 chances de trinquer',
    description: 'Rouge/noir, plus haut/bas, intérieur/extérieur, symbole. Chaque erreur se paie.',
    minPlayers: 2,
    image: '/images/game-bus.jpg',
    accent: '#38bdf8',
    duration: '10–20 min',
    category: 'cartes',
  },
  {
    id: 'rougenoir',
    title: 'Rouge ou Noir',
    tagline: 'Pile ou face version cartes',
    description: 'Mise sur la couleur. Bonne pioche tu donnes, mauvaise tu bois.',
    minPlayers: 2,
    image: '/images/game-kings.jpg',
    accent: '#f87171',
    duration: '5–15 min',
    category: 'rapide',
  },
  {
    id: 'chevaux',
    title: 'Course de chevaux',
    tagline: 'Parie sur une couleur, bois le retard',
    description: '4 as s’élancent. Chaque carte avance une couleur. Les perdants trinquent.',
    minPlayers: 2,
    image: '/images/game-horses.jpg',
    accent: '#facc15',
    duration: '10–20 min',
    category: 'cartes',
  },
  {
    id: 'tuprefere',
    title: 'Tu préfères…',
    tagline: 'Choisis ton camp, la minorité boit',
    description: 'Deux options impossibles. Vote. Ceux du petit camp trinquent.',
    minPlayers: 3,
    image: '/images/game-rather.jpg',
    accent: '#fb923c',
    duration: '10–25 min',
    category: 'defis',
  },
  {
    id: 'nioiuinon',
    title: 'Ni oui ni non',
    tagline: '30 secondes sans dire oui / non',
    description: 'Le groupe piège le joueur. Un oui ou un non = gorgées.',
    minPlayers: 2,
    image: '/images/game-never.jpg',
    accent: '#67e8f9',
    duration: '5–15 min',
    category: 'rapide',
  },
  {
    id: 'bac',
    title: 'Le Bac',
    tagline: 'Une lettre, des catégories, des gorgées',
    description: 'Trouve un mot par catégorie. Case vide = tu bois. Doublon = tu bois aussi.',
    minPlayers: 2,
    image: '/images/game-bac.jpg',
    accent: '#818cf8',
    duration: '15–30 min',
    category: 'classique',
  },
  {
    id: 'trois',
    title: '3-6-9',
    tagline: 'Compte, clap, bois',
    description: 'Compte à tour de rôle. Multiple ou chiffre 3/6/9 = clap. Rate = gorgées.',
    minPlayers: 2,
    image: '/images/game-dice.jpg',
    accent: '#4ade80',
    duration: '5–15 min',
    category: 'rapide',
  },
  {
    id: 'liardice',
    title: 'Liar Dice',
    tagline: 'Bluff, relance… ou menteur !',
    description:
      'Chacun a 5 dés secrets. Annonce un nombre de faces sur la table. Monte l’enchère ou crie menteur.',
    minPlayers: 2,
    image: '/images/game-liardice.jpg',
    accent: '#f59e0b',
    duration: '10–25 min',
    category: 'casino',
  },
  {
    id: 'mexicain',
    title: 'Le Mexicain',
    tagline: '2 dés, bluff et pression',
    description: 'Annonce un score plus fort que le précédent. On te croit… ou on te relance.',
    minPlayers: 2,
    image: '/images/game-dice.jpg',
    accent: '#f472b6',
    duration: '10–25 min',
    category: 'casino',
  },
  {
    id: 'mensonge',
    title: '2 vérités 1 mensonge',
    tagline: 'Trouve l’intox',
    description: 'Trois affirmations. Le groupe vote pour le mensonge. Les perdants boivent.',
    minPlayers: 3,
    image: '/images/game-vote.jpg',
    accent: '#e879f9',
    duration: '10–25 min',
    category: 'defis',
  },
  {
    id: 'imposteur',
    title: 'L’Imposteur',
    tagline: 'Un mot secret… sauf pour un',
    description: 'Tout le monde a le même mot, sauf l’imposteur. Discutez, votez, trinquez.',
    minPlayers: 4,
    image: '/images/game-impostor.jpg',
    accent: '#94a3b8',
    duration: '10–20 min',
    category: 'defis',
  },
  {
    id: 'beerpong',
    title: 'Beer Pong Digital',
    tagline: 'Vise les gobelets, bois les ratés',
    description: 'Deux équipes, 6 gobelets chacun. Rate ton tir = tu bois. Vide le camp adverse.',
    minPlayers: 2,
    image: '/images/game-beerpong.jpg',
    accent: '#fb7185',
    duration: '10–20 min',
    category: 'rapide',
  },
  {
    id: 'powerhour',
    title: 'Power Hour',
    tagline: 'Une gorgée toutes les 60 secondes',
    description: 'Minuteur collectif. Chaque minute, tout le monde trinque. Pause possible.',
    minPlayers: 2,
    image: '/images/hero-party.jpg',
    accent: '#fbbf24',
    duration: 'jusqu’à 60 min',
    category: 'classique',
  },
  {
    id: 'des',
    title: 'Dés de l’Apéro',
    tagline: 'Lance, lis, bois',
    description: 'Un dé décide du sort : gorgées, don, défi, relance, cul sec.',
    minPlayers: 2,
    image: '/images/game-dice.jpg',
    accent: '#fdba74',
    duration: '5–15 min',
    category: 'rapide',
  },
  {
    id: 'mime',
    title: 'Mime ou Bois',
    tagline: 'Fais deviner ou trinque',
    description: 'Mime le mot. Personne ne trouve ? Tu bois. Trouve = tu donnes.',
    minPlayers: 3,
    image: '/images/game-picolo.jpg',
    accent: '#86efac',
    duration: '10–20 min',
    category: 'defis',
  },
  {
    id: 'categories',
    title: 'Catégories',
    tagline: 'Le premier bloqué boit',
    description: 'Une catégorie, on tourne. Hésitation trop longue = gorgées.',
    minPlayers: 2,
    image: '/images/game-bac.jpg',
    accent: '#93c5fd',
    duration: '5–15 min',
    category: 'rapide',
  },
  {
    id: 'rps',
    title: 'PFC Fatal',
    tagline: 'Pierre feuille ciseaux en série',
    description: 'Duel. Le perdant boit. Enchaîne les combats autour de la table.',
    minPlayers: 2,
    image: '/images/game-rather.jpg',
    accent: '#fca5a5',
    duration: '5–10 min',
    category: 'rapide',
  },
  {
    id: 'hotseat',
    title: 'Hot Seat',
    tagline: 'Un joueur, toutes les questions',
    description: 'Le groupe grille quelqu’un. Refuser une question = 2 gorgées.',
    minPlayers: 3,
    image: '/images/game-truth.jpg',
    accent: '#fda4af',
    duration: '10–25 min',
    category: 'defis',
  },
]

export const PICOLO_CARDS: PicoloCard[] = [
  { kind: 'sip', text: '{p} boit 2 gorgées.' },
  { kind: 'sip', text: '{p} donne 3 gorgées à qui il/elle veut.' },
  { kind: 'sip', text: '{p} et {o} trinquent et boivent 2 gorgées.' },
  { kind: 'sip', text: 'Les prénoms commençant par une voyelle boivent 2 gorgées.' },
  { kind: 'sip', text: '{p} imite un animal. Le groupe vote : nul = 3 gorgées.' },
  { kind: 'sip', text: '{p} raconte son dernier crush. Hésitation = 2 gorgées.' },
  { kind: 'shot', text: '{p} choisit quelqu’un pour un mini-shot (ou 4 gorgées).' },
  { kind: 'shot', text: 'Le plus jeune de la table boit 3 gorgées.' },
  { kind: 'shot', text: 'Le plus vieux de la table boit 3 gorgées.' },
  { kind: 'all', text: 'TOUT LE MONDE boit 1 gorgée. Santé !' },
  { kind: 'all', text: 'Les filles boivent 2 gorgées. (Ou ceux qui s’identifient comme telles.)' },
  { kind: 'all', text: 'Les mecs boivent 2 gorgées.' },
  { kind: 'all', text: 'Ceux qui sont célibataires boivent 2 gorgées.' },
  { kind: 'all', text: 'Ceux en couple boivent 2 gorgées. Fidélité hydratée.' },
  { kind: 'all', text: 'Dernier(e) à poser le téléphone au centre boit 2 gorgées.' },
  { kind: 'vote', text: 'Votez : qui serait le pire coloc ? Cette personne boit 3 gorgées.' },
  { kind: 'vote', text: 'Votez : qui ment le plus ici ? 2 gorgées pour le gagnant.' },
  { kind: 'vote', text: 'Votez : qui finirait en garde à vue ce soir ? 2 gorgées.' },
  { kind: 'vote', text: 'Votez : qui a le pire historique de textos ? 2 gorgées.' },
  { kind: 'dare', text: '{p} envoie un emoji aléatoire à son 3e contact. Puis 1 gorgée.' },
  { kind: 'dare', text: '{p} parle avec un accent jusqu’au prochain tour, sinon 3 gorgées.' },
  { kind: 'dare', text: '{p} doit faire un compliment sincère à {o} ou boire 3 gorgées.' },
  { kind: 'dare', text: '{p} danse 10 secondes sans musique. Refus = 3 gorgées.' },
  { kind: 'dare', text: '{p} montre la dernière photo de sa galerie ou boit 4 gorgées.' },
  { kind: 'dare', text: '{p} laisse {o} poster une story (soft) ou boit un cul sec.' },
  { kind: 'rule', text: 'RÈGLE : interdiction de dire le prénom de {p}. Faute = 1 gorgée.' },
  { kind: 'rule', text: 'RÈGLE : on dit « monseigneur / madame » avant de parler. Faute = 1 gorgée.' },
  { kind: 'rule', text: 'RÈGLE : plus le droit de pointer du doigt. Faute = 1 gorgée.' },
  { kind: 'rule', text: 'RÈGLE : {p} est le maître du silence. Qui lui parle boit 1 gorgée.' },
  { kind: 'rule', text: 'RÈGLE : on trinque avant chaque gorgée. Oubli = +1 gorgée.' },
  { kind: 'duo', text: '{p} et {o} sont jumeaux : si l’un boit, l’autre boit aussi (3 tours).' },
  { kind: 'duo', text: '{p} invente un cocktail imaginaire. {o} doit le mimer ou boire 2 gorgées.' },
  { kind: 'duo', text: '{p} pose une question à {o}. Mauvaise réponse (groupe décide) = 2 gorgées.' },
  { kind: 'sip', text: '{p} boit autant de gorgées que de lettres dans son prénom (max 5).' },
  { kind: 'sip', text: 'Ceux qui ont déjà vomi à une soirée boivent 2 gorgées. Honneur.' },
  { kind: 'sip', text: '{p} choisit une catégorie (ex: bières). Chacun en cite une. Le premier bloqué boit.' },
  { kind: 'sip', text: 'Pierre-feuille-ciseaux entre {p} et {o}. Le perdant boit 3 gorgées.' },
  { kind: 'sip', text: '{p} doit rire pendant 8 secondes. Échec = 2 gorgées.' },
  { kind: 'sip', text: 'Le dernier arrivé à la soirée boit 2 gorgées.' },
  { kind: 'sip', text: '{p} donne son verre à {o} pour une gorgée surprise.' },
  { kind: 'dare', text: '{p} chante le refrain d’une chanson. Si personne ne reconnaît : 3 gorgées.' },
  { kind: 'dare', text: '{p} doit parler uniquement en questions pendant 1 tour.' },
  { kind: 'vote', text: 'Qui a le plus de chances de devenir célèbre ? Cette personne offre 2 gorgées.' },
  { kind: 'vote', text: 'Qui est le plus dramatique ? 2 gorgées + un petit discours.' },
  { kind: 'all', text: 'Waterfall ! Tout le monde boit, on s’arrête seulement quand le voisin de gauche s’arrête. {p} commence.' },
  { kind: 'shot', text: '{p} peut offrir un cul sec… ou le prendre. Décision en 5 secondes.' },
  { kind: 'sip', text: 'Ceux qui checkent leur tel en cachette ce soir : 2 gorgées.' },
  { kind: 'sip', text: '{p} raconte un secret mini-gênant ou boit 3 gorgées.' },
  { kind: 'rule', text: 'RÈGLE : plus de jurons. Chaque insulte = 1 gorgée.' },
  { kind: 'duo', text: '{p} et {o} doivent inventer un high-five signature. Rate = 2 gorgées chacun.' },
]

export const NEVER_PROMPTS = [
  'Je n’ai jamais embrassé quelqu’un dans ce groupe.',
  'Je n’ai jamais envoyé un texto à la mauvaise personne.',
  'Je n’ai jamais fantasmé sur un(e) prof / collègue.',
  'Je n’ai jamais dormi dans mes vêtements après une soirée.',
  'Je n’ai jamais menti sur mon âge.',
  'Je n’ai jamais ghosté quelqu’un.',
  'Je n’ai jamais fait semblant d’être bourré(e).',
  'Je n’ai jamais été vraiment amoureux(se).',
  'Je n’ai jamais stalké un ex sur les réseaux.',
  'Je n’ai jamais volé un verre / une conso dans une soirée.',
  'Je n’ai jamais dit « j’arrive » alors que j’étais encore au lit.',
  'Je n’ai jamais dansé sur une table.',
  'Je n’ai jamais eu un crush sur le/la meilleur(e) ami(e) de mon/ma partenaire.',
  'Je n’ai jamais pleuré en public (un peu trop).',
  'Je n’ai jamais cassé quelque chose chez quelqu’un sans le dire.',
  'Je n’ai jamais fait un discours complètement à côté.',
  'Je n’ai jamais utilisé le téléphone de quelqu’un sans demander.',
  'Je n’ai jamais inventé une excuse pour quitter une soirée.',
  'Je n’ai jamais embrassé plus d’une personne la même nuit.',
  'Je n’ai jamais été jaloux(se) d’un pote.',
  'Je n’ai jamais fait un pari stupide… et perdu.',
  'Je n’ai jamais chanté au karaoké (même pourri).',
  'Je n’ai jamais envoyé un message que je regrette encore.',
  'Je n’ai jamais fait une listes d’ex dans ma tête pendant un date.',
  'Je n’ai jamais menti pendant un jeu d’alcool.',
  'Je n’ai jamais eu un surnom gênant.',
  'Je n’ai jamais simulé une urgence pour éviter quelqu’un.',
  'Je n’ai jamais été recalé(e) en public.',
  'Je n’ai jamais gardé un secret vraiment lourd sur quelqu’un ici.',
  'Je n’ai jamais fait un toast complètement random.',
  'Je n’ai jamais pris le tapis roulant / l’ascenseur pour un étage.',
  'Je n’ai jamais dit « on reste juste potes » en mentant.',
  'Je n’ai jamais eu un plan cul qui a mal tourné.',
  'Je n’ai jamais oublié le prénom de quelqu’un juste après l’avoir entendu.',
  'Je n’ai jamais fait semblant d’aimer un cadeau.',
  'Je n’ai jamais regardé le téléphone de mon/ma partenaire en cachette.',
  'Je n’ai jamais été trop honnête après 3 verres.',
  'Je n’ai jamais promis « juste une dernière »… et j’ai menti.',
  'Je n’ai jamais eu un crush sur un personnage de série.',
  'Je n’ai jamais ri à un moment totalement inapproprié.',
]

export const VOTE_PROMPTS = [
  'Qui est le plus susceptible de devenir millionnaire ?',
  'Qui est le plus susceptible de se perdre en rentrant ?',
  'Qui est le plus dragueur / la plus dragueuse ?',
  'Qui est le plus susceptible de se marier en premier ?',
  'Qui a le pire goût musical ?',
  'Qui est le plus susceptible de lancer une bagarre (verbale) ?',
  'Qui survivrait le mieux à un zombie apocalypse ?',
  'Qui est le plus faux-cul (gentiment) ?',
  'Qui est le plus susceptible d’oublier son propre anniversaire ?',
  'Qui serait le pire président / la pire présidente ?',
  'Qui est le plus susceptible de déménager sans prévenir ?',
  'Qui est le plus addicte à son téléphone ?',
  'Qui est le plus susceptible de finir en larmes ce soir ?',
  'Qui a les pires excuses ?',
  'Qui est le plus susceptible de devenir influenceur(se) ?',
  'Qui est le plus radin ?',
  'Qui est le plus susceptible de cuisiner un plat immangeable ?',
  'Qui serait le meilleur coloc (honnêtement) ?',
  'Qui est le plus susceptible de tomber amoureux(se) ce mois-ci ?',
  'Qui ment le mieux ?',
  'Qui est le plus susceptible de rentrer pieds nus ?',
  'Qui a le plus gros ego (caché ou pas) ?',
  'Qui est le plus susceptible de tout raconter demain matin ?',
  'Qui ferait le meilleur complice de crime ?',
  'Qui est le plus susceptible de changer de vie du jour au lendemain ?',
  'Qui est le plus chaotique le samedi soir ?',
  'Qui devrait offrir le prochain tour ?',
  'Qui est le plus susceptible de se faire un tatouage impulsif ?',
  'Qui est le plus romantique (même en secret) ?',
  'Qui est le plus susceptible de parler à des inconnus au bar ?',
]

export const TRUTH_CARDS: TruthCard[] = [
  { type: 'verite', text: 'Quel est ton plus gros crush actuel (ou récent) ?' },
  { type: 'verite', text: 'Quelle est la chose la plus gênante que tu aies faite bourré(e) ?' },
  { type: 'verite', text: 'Qui dans ce groupe embrasserais-tu s’il le fallait absolument ?' },
  { type: 'verite', text: 'Quel secret n’as-tu jamais dit à tes parents ?' },
  { type: 'verite', text: 'Quelle est ta DM / ton texto le plus cringe ?' },
  { type: 'verite', text: 'As-tu déjà trahi la confiance d’un pote ?' },
  { type: 'verite', text: 'Quel est ton plus gros red flag perso ?' },
  { type: 'verite', text: 'Qui ici te connaît vraiment le moins ?' },
  { type: 'verite', text: 'Quelle est ton excuse préférée pour cancel ?' },
  { type: 'verite', text: 'Tu préfères perdre tous tes abonnés ou tous tes ex-contacts ?' },
  { type: 'verite', text: 'Quel mensonge racontes-tu encore régulièrement ?' },
  { type: 'verite', text: 'Quelle est la dernière fois que tu as été jaloux(se) ?' },
  { type: 'verite', text: 'Si tu devais swapper de vie avec quelqu’un ici, ce serait qui ?' },
  { type: 'verite', text: 'Quel est ton opinion impopulaire sur l’amour ?' },
  { type: 'verite', text: 'Tu as déjà eu un plan B pendant que tu fréquentais quelqu’un ?' },
  { type: 'action', text: 'Envoie « j’ai un truc à te dire… » à un contact au hasard, sans suite.' },
  { type: 'action', text: 'Fais un toast dramatique en l’honneur de quelqu’un ici.' },
  { type: 'action', text: 'Laisse le joueur à ta droite choisir ta prochaine gorgée + un mini défi.' },
  { type: 'action', text: 'Imite quelqu’un du groupe jusqu’à ce qu’on trouve qui.' },
  { type: 'action', text: 'Parle comme un commentateur sportif pendant 30 secondes.' },
  { type: 'action', text: 'Montre ton historique de recherche récent ou bois 4 gorgées.' },
  { type: 'action', text: 'Fais 10 squats en tenant ton verre… sans en renverser (sinon +2).' },
  { type: 'action', text: 'Échange de place avec quelqu’un et prends son accent.' },
  { type: 'action', text: 'Invente une choré de 5 secondes que tout le monde doit reproduire.' },
  { type: 'action', text: 'Lis à voix haute ton dernier message envoyé.' },
  { type: 'action', text: 'Ferme les yeux : le groupe te fait sentir un objet, tu devines ou tu bois.' },
  { type: 'action', text: 'Donne un surnom à chaque joueur. Ils le gardent 3 tours.' },
  { type: 'action', text: 'Appelle un pote (haut-parleur 5 sec) et dis juste « c’est l’heure ».' },
  { type: 'action', text: 'Fais le tour de table en disant un compliment gênant à chacun.' },
  { type: 'action', text: 'Joue à pile ou face : pile tu bois 2, face tu donnes 2.' },
]

export const BOTTLE_DARES = [
  '{p} boit 2 gorgées.',
  '{p} donne 2 gorgées à {o}.',
  '{p} doit faire un compliment à {o} ou boire 3 gorgées.',
  '{p} et {o} font pierre-feuille-ciseaux. Perdant boit 2 gorgées.',
  '{p} pose une question indiscrète à {o}. Silence = 2 gorgées.',
  '{p} choisit : vérité express ou 3 gorgées.',
  '{p} mime un film. Personne ne trouve en 20s = {p} boit.',
  '{p} trinque avec tout le monde, puis boit 1 gorgée.',
  '{p} invente une règle jusqu’à la prochaine rotation.',
  '{p} désigne qui boit un cul sec… ou le prend.',
]

export const KINGS_RULES: Record<string, { title: string; rule: string }> = {
  A: { title: 'Waterfall', rule: 'Tout le monde boit. Tu t’arrêtes seulement quand le voisin de gauche s’arrête. Le tireur commence.' },
  '2': { title: 'Tu donnes', rule: 'Donne 2 gorgées à un ou plusieurs joueurs.' },
  '3': { title: 'Tu bois', rule: 'Tu bois 2 gorgées. Pas de débat.' },
  '4': { title: 'Les filles', rule: 'Toutes les joueuses boivent 2 gorgées.' },
  '5': { title: 'Les gars', rule: 'Tous les joueurs masculins boivent 2 gorgées.' },
  '6': { title: 'Ça passe', rule: 'Tout le monde passe son verre à gauche et boit une gorgée du nouveau verre (ou mime + 1 gorgée du sien).' },
  '7': { title: 'Ciel', rule: 'Dernier à lever la main au ciel boit 2 gorgées.' },
  '8': { title: 'Mate', rule: 'Choisis un mate. Dès que tu bois, il/elle boit aussi (jusqu’à la fin ou un nouveau 8).' },
  '9': { title: 'Rime', rule: 'Dis un mot. Chacun doit rimer. Le premier qui bloque boit 3 gorgées.' },
  '10': { title: 'Catégorie', rule: 'Annonce une catégorie. On tourne. Le premier bloqué boit 3 gorgées.' },
  J: { title: 'Règle', rule: 'Inventes une règle pour toute la partie. Toute faute = 1 gorgée.' },
  Q: { title: 'Question', rule: 'Tu poses une question à quelqu’un. Il/elle ne peut répondre que par une autre question. Qui casse boit 2 gorgées.' },
  K: { title: 'Le Roi', rule: 'Verse un peu de ton verre dans le verre du milieu. Le 4e roi le descend cul sec !' },
}

export const RATHER_PAIRS: [string, string][] = [
  ['Plus jamais de fromage', 'Plus jamais de chocolat'],
  ['Être toujours 15 min en retard', 'Être toujours 2h en avance'],
  ['Lire dans les pensées', 'Être invisible 1h/jour'],
  ['Perdre tous tes abonnés', 'Perdre tout ton historique de messages'],
  ['Un date avec ton crush d’enfance', 'Un resto avec ton ex'],
  ['Chanter faux en public', 'Danser seul(e) en boîte'],
  ['Savoir la date de ta mort', 'Savoir qui sera à ton enterrement'],
  ['Toujours dire la vérité', 'Ne plus pouvoir parler 1 jour/semaine'],
  ['Vivre sans musique', 'Vivre sans séries / films'],
  ['Être célèbre et détesté', 'Être inconnu et adoré de tes proches'],
  ['Un salaire x3 sans passion', 'Ta passion pour 1 SMIC'],
  ['Voyager sans valise', 'Rester chez toi 1 an tout payé'],
  ['Oublier tes ex', 'Qu’ils t’oublient tous'],
  ['Porter le même t-shirt 1 mois', 'Pas de téléphone 1 semaine'],
  ['Être le plus drôle du groupe', 'Être le plus beau / belle du groupe'],
  ['Un power-point de tes DMs', 'Un diapo de tes photos recadrées'],
  ['Toujours choisir le resto', 'Ne plus jamais choisir'],
  ['Parler comme un pirate 24h', 'Marcher à reculons 1h'],
  ['Un tatouage choisi par la table', 'Une coupe choisie par la table'],
  ['Boire que de l’eau ce soir', 'Raconter ton plus gros secret'],
]

export const HOTSEAT_QS = [
  'Qui ici te saoulerait en coloc ?',
  'Quel est ton red flag le plus assumé ?',
  'Qui embrasserais-tu s’il fallait absolument ?',
  'Quelle est ta DM la plus cringe ?',
  'Tu caches quoi à tes parents encore aujourd’hui ?',
  'Quelle est ta pire soirée ?',
  'Sur qui as-tu déjà eu un crush secret ici ?',
  'Quel mensonge racontes-tu encore ?',
  'Si tu devais swapper de vie avec quelqu’un ici, ce serait qui ?',
  'Quelle est ta plus grosse jalousie récente ?',
  'Tu préfères perdre quel pote (hypothétique, sois cruel) ?',
  'Quel est ton opinion impopulaire ?',
  'Décris ton type en 3 mots, sans filtre.',
  'Quelle est la dernière fois que tu as ghosté ?',
  'Qui ici ferait le pire plan à 3 (humour) ?',
  'Quel est ton excuse fétiche pour cancel ?',
  'Tu as déjà trahi la confiance d’un pote ?',
  'Si on fouillait ton tél, on trouverait quoi ?',
]

export const MIME_WORDS = [
  'Karaoke catastrophique',
  'Premier rencard',
  'Réveil après une cuite',
  'Influencé TikTok',
  'Match de foot',
  'Drague en boîte',
  'Entretien d’embauche',
  'Yoga naze',
  'Pirate',
  'Serveur débordé',
  'Chat qui juge',
  'DJ de mariage',
  'Mannequin',
  'Vampire timide',
  'Prof en crise',
  'Astronaute',
  'Stand-up raté',
  'Tinder date',
  'Mamie au supermarché',
  'Super-héros sans pouvoir',
]

export const CATEGORY_WORDS = [
  'Marques d’alcool',
  'Capitales européennes',
  'Films français',
  'Chanteurs / chanteuses',
  'Animaux marins',
  'Métiers bizarres',
  'Trucs qu’on trouve dans un frigo',
  'Jeux vidéo',
  'Sports olympiques',
  'Fromages',
  'Séries Netflix',
  'Pays qui commencent par une voyelle',
  'Prénoms en L',
  'Trucs gênants en soirée',
  'Célébrités françaises',
  'Plats de grand-mère',
  'Applications de téléphone',
  'Insectes',
  'Voitures',
  'Mots liés à l’amour',
]

export const IMPOSTOR_WORDS = [
  'Tequila',
  'Karaoké',
  'Tinder',
  'After',
  'Pastis',
  'Jacuzzi',
  'Festival',
  'Brunch',
  'Shot',
  'Disco',
  'Mojito',
  'Camping',
  'Poker',
  'Sushi',
  'Marathon',
  'Sauna',
  'Plage',
  'Halloween',
  'Raclette',
  'TGV',
]

export const LIE_STARTERS = [
  'J’ai déjà…',
  'Quand j’étais mineur(e)…',
  'Au travail / à l’école…',
  'En vacances…',
  'Un soir de fête…',
]

export const NOYES_QS = [
  'T’es prêt(e) ?',
  'Tu veux un verre ?',
  'C’est toi le plus soûl ?',
  'Tu confirmes ?',
  'On peut commencer ?',
  'Tu aimes ce jeu ?',
  'C’était non, en fait ?',
  'Tu dis souvent oui trop vite ?',
  'Tu es d’accord avec la table ?',
  'C’est clair pour toi ?',
]

export const BAC_CATS = ['Prénom', 'Ville / pays', 'Truc à manger', 'Animal', 'Métier', 'Dans un bar']
export const BAC_LETTERS = 'ABCDEFGHIJKLMNOPRSTV'.split('')

export const SUGGESTED_NAMES = ['Léo', 'Inès', 'Max', 'Chloé', 'Nico', 'Sarah', 'Tom', 'Léa']

export const PLAYER_COLORS = [
  '#f43f9d',
  '#22d3ee',
  '#fbbf24',
  '#a78bfa',
  '#34d399',
  '#fb7185',
  '#60a5fa',
  '#f97316',
  '#e879f9',
  '#2dd4bf',
]